services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pr_reviewer_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pr-network
    container_name: db  # ← Явно задаем имя контейнера

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://pguser:password@db:5432/pr_reviewer_db?sslmode=disable"
    depends_on:
      - db
    networks:
      - pr-network

networks:
  pr-network:
    driver: bridge
    name: pr-reviewer-network

volumes:
  postgres_data: