services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pr_reviewer_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d pr_reviewer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: novvalea/pr-reviewer-service:latest
    #build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://pguser:password@db:5432/pr_reviewer_db?sslmode=disable"
      PORT: "8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
